config/routes.rb
Rails.application.routes.draw do

  get '/' => "pages#home"

  resources :categories
    get 'categories/:id/delete' =>
  'categories#delete', :as => :categories_delete
  
  get 'categories/index'

  get 'categories/show'

  get 'categories/new'

  get 'categories/edit'

  get 'categories/delete'

  get 'pages/home'

  get 'pages/erb_demo'

  get 'pages/render_demo'

  get 'pages/redirect_demo'

  root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def delete
  end

  private

  def category_params
    params.require(:category).permit(:name, :thumburl)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home 
	end

	def erb_demo
	end

	def render_demo
		render :home
	end

	def redirect_demo
		redirect_to(:action => 'home')
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>


<h1>LIsting Cats</h1>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Thumburl</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<%  %>
			<tr>
				<td><%= %></td>
				<td><%= %></td>
				<td><%= link_to 'Show', category_path(category) %></td>
				<td><%= link_to 'Edit', category_path(category) %></td>
				<td><%= link_to 'Destroy', category, method: :delete, data: { confirm: "Positive?"} %></td>
			</tr>
		<% #end loop %>
	</tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EtsyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/topnav' %>

<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1>Shop directly from people around the world.</h1>
      </div>
    </div>
  </div>
</div>

<div class="trending">
  <div class="container">
    <h2>Recent Favorites</h2>
    <p>Discover finds from around the marketplace.</p>
    <div class="row trending-listing">
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="https://img1.etsystatic.com/034/0/6705395/il_340x270.542888787_ggy4.jpg">
          <div class="caption">
            <span class="listing-title">Large gold leather bag</span>
            <span class="listing-price">$100.00</span>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="https://img1.etsystatic.com/010/0/6957353/il_340x270.427320275_pxiv.jpg">
          <div class="caption">
            <span class="listing-title">Large gold leather bag</span>
            <span class="listing-price">$15.00</span>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="https://img1.etsystatic.com/038/0/6566540/il_340x270.566511947_1r1t.jpg">
          <div class="caption">
            <span class="listing-title">Large gold leather bag</span>
            <span class="listing-price">$160.00</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/pages/redirect_demo.html.erb
<% "redirect template" %>